name: MinecraftJobPlugin
main: org.blog.minecraftJobPlugin.JobPlugin
version: 1.0.0
api-version: "1.21"
author: junggyeol4444
description: "직업 시스템 플러그인 (직업·스킬·퀘스트·상점 등)"

depend: [Vault]

commands:
  job:
    description: "직업 관련 명령어"
    usage: "/job [info|list|roll|select]"
    permission: minecraftjob.job
    permission-message: "§c권한이 없습니다."
  shop:
    description: "직업 전용 상점 열기"
    usage: "/shop"
    permission: minecraftjob.shop
    permission-message: "§c권한이 없습니다."
  upgrade:
    description: "손에 든 장비 업그레이드 (비용 차감)"
    usage: "/upgrade"
    permission: minecraftjob.upgrade
    permission-message: "§c권한이 없습니다."

permissions:
  minecraftjob.job:
    description: "직업 명령어 사용 권한"
    default: true
  minecraftjob.shop:
    description: "직업 상점 사용 권한"
    default: true
  minecraftjob.upgrade:
    description: "장비 업그레이드 권한"
    default: true